AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics:
  Enabled: false
